[package]
name = "transitionable-abort-tests"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
transitionable = { path = "..", features = ["_test"] }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
